#ifndef CONFIGURATIONS_H
#define CONFIGURATIONS_H

#define COLOR_WHITE_HEX 0xFFFFFF
#define COLOR_BLACK_HEX 0x000000
#define GAP 8 

#define BACKGROUND_COLOR_OF_MAIN_WINDOW COLOR_WHITE_HEX
#define BACKGROUND_COLOR_OF_BIT_WINDOW COLOR_WHITE_HEX
#define PAINT_COLOR COLOR_BLACK_HEX
#define ERASE_COLOR BACKGROUND_COLOR_OF_BIT_WINDOW

#define BGCM BACKGROUND_COLOR_OF_MAIN_WINDOW
#define BGCB BACKGROUND_COLOR_OF_BIT_WINDOW

#define X_OFFSET 2
#define Y_OFFSET 2

#define FONT_SIZE 50
#define _XK_ESCAPE 0xff1b

#define EXIT_BUTTON_TEXT "X"
#define EXIT_BUTTON_TEXT_LENGTH 1


#define MAIN_WINDOW_WIDTH 800
#define MAIN_WINDOW_HEIGHT 800
#define HELIX_RADIUS 40
#define HELIX_ARCS 4
#define HELIX_ORB_RADIUS 5
#define DEGREE_STEP 5

#define STEPS_PER_ARC 180/DEGREE_STEP
#define DOTS (4*STEPS_PER_ARC + STEPS_PER_ARC + STEPS_PER_ARC/2) 
#define ARC_DELTA HELIX_RADIUS*0.5

#define VELOCITY_PSEUDO 1<<14
#endif //END OF CONFIGURATIONS_H