#ifndef CONFIGURATIONS_H
#define CONFIGURATIONS_H

#define BIT_WINDOW_AMOUNT 32
#define BIT_WINDOW_ROWS_AMOUNT 2
#define COLOR_WHITE_HEX 0xFFFFFF
#define COLOR_BLACK_HEX 0x000000
#define GAP 8 

#define BACKGROUND_COLOR_OF_MAIN_WINDOW COLOR_WHITE_HEX
#define BACKGROUND_COLOR_OF_BIT_WINDOW COLOR_WHITE_HEX
#define PAINT_COLOR COLOR_BLACK_HEX
#define ERASE_COLOR BACKGROUND_COLOR_OF_BIT_WINDOW

#define BGCM BACKGROUND_COLOR_OF_MAIN_WINDOW
#define BGCB BACKGROUND_COLOR_OF_BIT_WINDOW

#define X_OFFSET 2
#define Y_OFFSET 2


#define _XK_ESCAPE 0xff1b
#define BIT_WINDOW_WIDTH 48
#define BIT_WINDOW_HEIGHT BIT_WINDOW_WIDTH 
#define EXIT_BUTTON_TEXT "X"
#define EXIT_BUTTON_TEXT_LENGTH 1
#define EXIT_WINDOW_HEIGHT (BIT_WINDOW_HEIGHT * BIT_WINDOW_ROWS_AMOUNT + Y_OFFSET)
#define EXIT_WINDOW_WIDTH EXIT_WINDOW_HEIGHT

#define BIT_ROW_WINDOW_WIDTH (BIT_WINDOW_WIDTH * BIT_WINDOW_AMOUNT + X_OFFSET * (BIT_WINDOW_AMOUNT-1) + GAP * (BIT_WINDOW_AMOUNT/4-1))
#define BIT_ROW_WINDOW_HEIGHT BIT_WINDOW_HEIGHT

#define MAIN_WINDOW_WIDTH (BIT_ROW_WINDOW_WIDTH + X_OFFSET * 2 + EXIT_WINDOW_WIDTH)
#define MAIN_WINDOW_HEIGHT (BIT_ROW_WINDOW_HEIGHT * BIT_WINDOW_ROWS_AMOUNT + Y_OFFSET * 3)

#endif //END OF CONFIGURATIONS_H